[0m2024-02-29 12:57:12 V/Net 3079809050: Invalidate caches because hash file not available.[0m
[0m2024-02-29 12:57:12 V/Net 3079809050: No server list cached.[0m
[92m2024-02-29 12:57:12 I/Net 3079809050: EncryptService SPI is not provided, sso secure ecdh will not be initialized.[0m
[92m2024-02-29 12:57:12 I/Net 3079809050: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2024-02-29 12:57:13 I/Net 3079809050: Successfully fetched ecdh public key from server.[0m
[0m2024-02-29 12:57:13 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 12:57:13 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Password@1643121695[0m
[0m2024-02-29 12:57:13 V/Net 3079809050: Send: wtlogin.login(9:password-login)[0m
[0m2024-02-29 12:57:13 V/Net 3079809050: Recv: wtlogin.login[0m
[93m2024-02-29 12:57:57 W/Net 3079809050: Failed with auth method: Password@1643121695
com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled
	at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver.onSolveSliderCaptcha$mirai_login_solver_sakura(SakuraLoginSolver.kt:174)
	at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver$onSolveSliderCaptcha$2.invokeSuspend(SakuraLoginSolver.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m
[0m2024-02-29 12:57:57 V/Net 3079809050: [AuthControl/resume] Fire auth failed with cause: com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled[0m
[93m2024-02-29 12:57:57 W/Net 3079809050: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
[0m
[92m2024-02-29 12:57:57 I/Net 3079809050: ECDH key is valid.[0m
[0m2024-02-29 12:57:57 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 12:57:57 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Error[com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled]@87217362[0m
[93m2024-02-29 12:57:57 W/Net 3079809050: Failed with auth method: Error[com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled]@87217362
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled
	at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver.onSolveSliderCaptcha$mirai_login_solver_sakura(SakuraLoginSolver.kt:174)
	at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver$onSolveSliderCaptcha$2.invokeSuspend(SakuraLoginSolver.kt)
	... 6 more
[0m
[93m2024-02-29 12:57:57 W/Net 3079809050: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	... 6 more
	Suppressed: com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled
		at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver.onSolveSliderCaptcha$mirai_login_solver_sakura(SakuraLoginSolver.kt:174)
		at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver$onSolveSliderCaptcha$2.invokeSuspend(SakuraLoginSolver.kt)
		... 6 more
Caused by: [CIRCULAR REFERENCE: com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled]
[0m
[93m2024-02-29 12:57:57 W/Net 3079809050: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)[0m
[0m2024-02-29 12:59:47 V/Net 3079809050: Validated caches.[0m
[0m2024-02-29 12:59:47 V/Net 3079809050: No server list cached.[0m
[92m2024-02-29 12:59:48 I/Net 3079809050: EncryptService SPI is not provided, sso secure ecdh will not be initialized.[0m
[92m2024-02-29 12:59:48 I/Net 3079809050: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2024-02-29 12:59:49 I/Net 3079809050: Successfully fetched ecdh public key from server.[0m
[0m2024-02-29 12:59:49 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 12:59:49 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Password@79993145[0m
[0m2024-02-29 12:59:49 V/Net 3079809050: Send: wtlogin.login(9:password-login)[0m
[0m2024-02-29 12:59:49 V/Net 3079809050: Recv: wtlogin.login[0m
[0m2024-02-29 13:00:05 V/Net 3079809050: Send: wtlogin.login(2:submit-slider)[0m
[0m2024-02-29 13:00:05 V/Net 3079809050: Recv: wtlogin.login[0m
[93m2024-02-29 13:00:05 W/Net 3079809050: Failed with auth method: Password@79993145
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m
[0m2024-02-29 13:00:05 V/Net 3079809050: [AuthControl/resume] Fire auth failed with cause: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)[0m
[93m2024-02-29 13:00:05 W/Net 3079809050: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
[0m
[92m2024-02-29 13:00:05 I/Net 3079809050: ECDH key is valid.[0m
[0m2024-02-29 13:00:05 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 13:00:05 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)]@1430728266[0m
[93m2024-02-29 13:00:05 W/Net 3079809050: Failed with auth method: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)]@1430728266
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	... 5 more
[0m
[93m2024-02-29 13:00:05 W/Net 3079809050: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	... 6 more
	Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)]
[0m
[93m2024-02-29 13:00:05 W/Net 3079809050: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)[0m
[0m2024-02-29 13:16:58 V/Net 3079809050: Invalidate caches because hash file not available.[0m
[0m2024-02-29 13:16:58 V/Net 3079809050: No server list cached.[0m
[92m2024-02-29 13:16:59 I/Net 3079809050: EncryptService SPI is not provided, sso secure ecdh will not be initialized.[0m
[92m2024-02-29 13:16:59 I/Net 3079809050: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2024-02-29 13:16:59 I/Net 3079809050: Successfully fetched ecdh public key from server.[0m
[0m2024-02-29 13:16:59 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 13:16:59 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Password@1789517207[0m
[0m2024-02-29 13:16:59 V/Net 3079809050: Send: wtlogin.login(9:password-login)[0m
[0m2024-02-29 13:16:59 V/Net 3079809050: Recv: wtlogin.login[0m
[0m2024-02-29 13:17:13 V/Net 3079809050: Send: wtlogin.login(2:submit-slider)[0m
[0m2024-02-29 13:17:14 V/Net 3079809050: Recv: wtlogin.login[0m
[93m2024-02-29 13:17:14 W/Net 3079809050: Failed with auth method: Password@1789517207
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m
[0m2024-02-29 13:17:14 V/Net 3079809050: [AuthControl/resume] Fire auth failed with cause: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)[0m
[93m2024-02-29 13:17:14 W/Net 3079809050: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
[0m
[92m2024-02-29 13:17:14 I/Net 3079809050: ECDH key is valid.[0m
[0m2024-02-29 13:17:14 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 13:17:14 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)]@429121575[0m
[93m2024-02-29 13:17:14 W/Net 3079809050: Failed with auth method: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)]@429121575
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	... 5 more
[0m
[93m2024-02-29 13:17:14 W/Net 3079809050: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	... 6 more
	Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)]
[0m
[93m2024-02-29 13:17:14 W/Net 3079809050: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)[0m
[0m2024-02-29 13:33:16 V/Net 3079809050: Hash not match. Invaliding caches.....[0m
[0m2024-02-29 13:33:16 V/Net 3079809050: No server list cached.[0m
[92m2024-02-29 13:33:16 I/Net 3079809050: EncryptService SPI is not provided, sso secure ecdh will not be initialized.[0m
[92m2024-02-29 13:33:16 I/Net 3079809050: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2024-02-29 13:33:16 I/Net 3079809050: Successfully fetched ecdh public key from server.[0m
[0m2024-02-29 13:33:16 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 13:33:16 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Password@1069108422[0m
[0m2024-02-29 13:33:16 V/Net 3079809050: Send: wtlogin.login(9:password-login)[0m
[0m2024-02-29 13:33:17 V/Net 3079809050: Recv: wtlogin.login[0m
[0m2024-02-29 13:33:51 V/Net 3079809050: Send: wtlogin.login(2:submit-slider)[0m
[0m2024-02-29 13:33:51 V/Net 3079809050: Recv: wtlogin.login[0m
[93m2024-02-29 13:33:51 W/Net 3079809050: Failed with auth method: Password@1069108422
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m
[0m2024-02-29 13:33:51 V/Net 3079809050: [AuthControl/resume] Fire auth failed with cause: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)[0m
[93m2024-02-29 13:33:51 W/Net 3079809050: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
[0m
[92m2024-02-29 13:33:51 I/Net 3079809050: ECDH key is valid.[0m
[0m2024-02-29 13:33:51 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 13:33:51 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)]@1735365878[0m
[93m2024-02-29 13:33:51 W/Net 3079809050: Failed with auth method: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)]@1735365878
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	... 5 more
[0m
[93m2024-02-29 13:33:51 W/Net 3079809050: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	... 6 more
	Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)]
[0m
[93m2024-02-29 13:33:51 W/Net 3079809050: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)[0m
[0m2024-02-29 13:34:03 V/Net 3079809050: Validated caches.[0m
[0m2024-02-29 13:34:03 V/Net 3079809050: No server list cached.[0m
[92m2024-02-29 13:34:03 I/Net 3079809050: EncryptService SPI is not provided, sso secure ecdh will not be initialized.[0m
[92m2024-02-29 13:34:03 I/Net 3079809050: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2024-02-29 13:34:03 I/Net 3079809050: Successfully fetched ecdh public key from server.[0m
[0m2024-02-29 13:34:03 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 13:34:03 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Password@441861350[0m
[0m2024-02-29 13:34:03 V/Net 3079809050: Send: wtlogin.login(9:password-login)[0m
[0m2024-02-29 13:34:04 V/Net 3079809050: Recv: wtlogin.login[0m
[0m2024-02-29 13:34:18 V/Net 3079809050: Send: wtlogin.login(2:submit-slider)[0m
[0m2024-02-29 13:34:19 V/Net 3079809050: Recv: wtlogin.login[0m
[93m2024-02-29 13:34:19 W/Net 3079809050: Failed with auth method: Password@441861350
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m
[0m2024-02-29 13:34:19 V/Net 3079809050: [AuthControl/resume] Fire auth failed with cause: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)[0m
[93m2024-02-29 13:34:19 W/Net 3079809050: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
[0m
[92m2024-02-29 13:34:19 I/Net 3079809050: ECDH key is valid.[0m
[0m2024-02-29 13:34:19 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 13:34:19 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)]@1791978989[0m
[93m2024-02-29 13:34:19 W/Net 3079809050: Failed with auth method: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)]@1791978989
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	... 5 more
[0m
[93m2024-02-29 13:34:19 W/Net 3079809050: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	... 6 more
	Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)]
[0m
[93m2024-02-29 13:34:19 W/Net 3079809050: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)[0m
[0m2024-02-29 13:38:22 V/Net 3079809050: Hash not match. Invaliding caches.....[0m
[0m2024-02-29 13:38:22 V/Net 3079809050: No server list cached.[0m
[92m2024-02-29 13:38:23 I/Net 3079809050: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2024-02-29 13:38:24 I/Net 3079809050: Successfully fetched ecdh public key from server.[0m
[0m2024-02-29 13:38:24 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 13:38:24 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Password@1321654615[0m
[0m2024-02-29 13:38:24 V/Net 3079809050: Send: wtlogin.login(9:password-login)[0m
[0m2024-02-29 13:38:24 V/Net 3079809050: Recv: wtlogin.login[0m
[0m2024-02-29 13:38:58 V/Net 3079809050: Send: wtlogin.login(2:submit-slider)[0m
[93m2024-02-29 13:38:58 W/Net 3079809050: Failed with auth method: Password@1321654615
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m
[0m2024-02-29 13:38:58 V/Net 3079809050: Recv: wtlogin.login[0m
[0m2024-02-29 13:38:58 V/Net 3079809050: [AuthControl/resume] Fire auth failed with cause: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)[0m
[93m2024-02-29 13:38:58 W/Net 3079809050: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
[0m
[92m2024-02-29 13:38:58 I/Net 3079809050: ECDH key is valid.[0m
[0m2024-02-29 13:38:58 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 13:38:58 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)]@1283152442[0m
[93m2024-02-29 13:38:58 W/Net 3079809050: Failed with auth method: Error[net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)]@1283152442
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	... 5 more
[0m
[93m2024-02-29 13:38:58 W/Net 3079809050: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	... 6 more
	Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3079809050), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)]
[0m
[93m2024-02-29 13:38:58 W/Net 3079809050: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)[0m
[0m2024-02-29 14:10:51 V/Net 3079809050: Hash not match. Invaliding caches.....[0m
[0m2024-02-29 14:10:51 V/Net 3079809050: No server list cached.[0m
[92m2024-02-29 14:10:53 I/Net 3079809050: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2024-02-29 14:10:54 I/Net 3079809050: Successfully fetched ecdh public key from server.[0m
[0m2024-02-29 14:10:54 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 14:10:54 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Password@1044001421[0m
[0m2024-02-29 14:10:55 V/Net 3079809050: Send: wtlogin.login(9:password-login)[0m
[0m2024-02-29 14:10:55 V/Net 3079809050: Recv: wtlogin.login[0m
[93m2024-02-29 14:11:11 W/Net 3079809050: Failed with auth method: Password@1044001421
com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled
	at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver.onSolveSliderCaptcha$mirai_login_solver_sakura(SakuraLoginSolver.kt:174)
	at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver$onSolveSliderCaptcha$2.invokeSuspend(SakuraLoginSolver.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m
[0m2024-02-29 14:11:11 V/Net 3079809050: [AuthControl/resume] Fire auth failed with cause: com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled[0m
[93m2024-02-29 14:11:11 W/Net 3079809050: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
[0m
[92m2024-02-29 14:11:11 I/Net 3079809050: ECDH key is valid.[0m
[0m2024-02-29 14:11:11 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 14:11:11 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Error[com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled]@1246110608[0m
[93m2024-02-29 14:11:11 W/Net 3079809050: Failed with auth method: Error[com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled]@1246110608
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled
	at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver.onSolveSliderCaptcha$mirai_login_solver_sakura(SakuraLoginSolver.kt:174)
	at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver$onSolveSliderCaptcha$2.invokeSuspend(SakuraLoginSolver.kt)
	... 6 more
[0m
[93m2024-02-29 14:11:11 W/Net 3079809050: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	... 6 more
	Suppressed: com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled
		at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver.onSolveSliderCaptcha$mirai_login_solver_sakura(SakuraLoginSolver.kt:174)
		at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver$onSolveSliderCaptcha$2.invokeSuspend(SakuraLoginSolver.kt)
		... 6 more
Caused by: [CIRCULAR REFERENCE: com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled]
[0m
[93m2024-02-29 14:11:11 W/Net 3079809050: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)[0m
[0m2024-02-29 14:11:33 V/Net 3079809050: Validated caches.[0m
[0m2024-02-29 14:11:33 V/Net 3079809050: No server list cached.[0m
[92m2024-02-29 14:11:35 I/Net 3079809050: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2024-02-29 14:11:36 I/Net 3079809050: Successfully fetched ecdh public key from server.[0m
[0m2024-02-29 14:11:36 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 14:11:36 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Password@1379023159[0m
[0m2024-02-29 14:11:37 V/Net 3079809050: Send: wtlogin.login(9:password-login)[0m
[0m2024-02-29 14:11:37 V/Net 3079809050: Recv: wtlogin.login[0m
[0m2024-02-29 14:11:47 V/Net 3079809050: Send: wtlogin.login(2:submit-slider)[0m
[0m2024-02-29 14:11:47 V/Net 3079809050: Recv: wtlogin.login[0m
[0m2024-02-29 14:13:06 V/Net 3079809050: Send: wtlogin.login(9:password-login)[0m
[0m2024-02-29 14:13:06 V/Net 3079809050: Recv: wtlogin.login[0m
[93m2024-02-29 14:13:08 W/Net 3079809050: Failed with auth method: Password@1379023159
com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled
	at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver.onSolveSliderCaptcha$mirai_login_solver_sakura(SakuraLoginSolver.kt:174)
	at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver$onSolveSliderCaptcha$2.invokeSuspend(SakuraLoginSolver.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[0m
[0m2024-02-29 14:13:08 V/Net 3079809050: [AuthControl/resume] Fire auth failed with cause: com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled[0m
[93m2024-02-29 14:13:08 W/Net 3079809050: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
[0m
[92m2024-02-29 14:13:08 I/Net 3079809050: ECDH key is valid.[0m
[0m2024-02-29 14:13:08 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 14:13:08 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Error[com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled]@219682356[0m
[93m2024-02-29 14:13:08 W/Net 3079809050: Failed with auth method: Error[com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled]@219682356
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled
	at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver.onSolveSliderCaptcha$mirai_login_solver_sakura(SakuraLoginSolver.kt:174)
	at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver$onSolveSliderCaptcha$2.invokeSuspend(SakuraLoginSolver.kt)
	... 6 more
[0m
[93m2024-02-29 14:13:08 W/Net 3079809050: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	... 6 more
	Suppressed: com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled
		at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver.onSolveSliderCaptcha$mirai_login_solver_sakura(SakuraLoginSolver.kt:174)
		at mirai-login-solver-sakura-0.0.12.mirai2.jar//com.kasukusakura.mlss.resolver.SakuraLoginSolver$onSolveSliderCaptcha$2.invokeSuspend(SakuraLoginSolver.kt)
		... 6 more
Caused by: [CIRCULAR REFERENCE: com.kasukusakura.mlss.resolver.UnsafeDeviceLoginVerifyCancelledException: Cancelled]
[0m
[93m2024-02-29 14:13:08 W/Net 3079809050: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)[0m
[0m2024-02-29 14:13:10 V/Net 3079809050: Validated caches.[0m
[0m2024-02-29 14:13:10 V/Net 3079809050: No server list cached.[0m
[92m2024-02-29 14:13:12 I/Net 3079809050: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2024-02-29 14:13:13 I/Net 3079809050: Successfully fetched ecdh public key from server.[0m
[0m2024-02-29 14:13:13 V/Net 3079809050: [AuthControl/acquire] Acquiring auth method[0m
[96m2024-02-29 14:13:13 D/Net 3079809050: [AuthControl/acquire] Authorization responded: Password@1857799868[0m
[0m2024-02-29 14:13:14 V/Net 3079809050: Send: wtlogin.login(9:password-login)[0m
[0m2024-02-29 14:13:14 V/Net 3079809050: Recv: wtlogin.login[0m
[0m2024-02-29 14:13:28 V/Net 3079809050: Send: wtlogin.login(2:submit-slider)[0m
[0m2024-02-29 14:13:28 V/Net 3079809050: Recv: wtlogin.login[0m
[0m2024-02-29 14:13:28 V/Net 3079809050: [AuthControl/resume] Fire auth completed[0m
[0m2024-02-29 14:13:28 V/Net 3079809050: Send: StatSvc.register(online)[0m
[92m2024-02-29 14:13:29 I/Net 3079809050: Server time updated, serverTime: 1709187208, diff: -1ms=-0.001s[0m
[0m2024-02-29 14:13:29 V/Net 3079809050: Recv: StatSvc.register[0m
[0m2024-02-29 14:13:29 V/Net 3079809050: No BdhSession cache[0m
[92m2024-02-29 14:13:29 I/Net 3079809050: Syncing friend message history...[0m
[92m2024-02-29 14:13:29 I/Net 3079809050: Start loading friend list...[0m
[92m2024-02-29 14:13:29 I/Net 3079809050: Start loading stranger list...[0m
[92m2024-02-29 14:13:29 I/Net 3079809050: Start loading friendGroup list...[0m
[0m2024-02-29 14:13:29 V/Net 3079809050: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[0m2024-02-29 14:13:29 V/Net 3079809050: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2024-02-29 14:13:29 V/Net 3079809050: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[0m2024-02-29 14:13:29 V/Net 3079809050: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2024-02-29 14:13:29 V/Net 3079809050: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2024-02-29 14:13:29 V/Net 3079809050: Recv: OidbSvc.0x5d2_0[0m
[92m2024-02-29 14:13:29 I/Net 3079809050: Successfully loaded stranger list: 0 in total[0m
[0m2024-02-29 14:13:29 V/Net 3079809050: Recv: StatSvc.GetDevLoginInfo[0m
[92m2024-02-29 14:13:29 I/Net 3079809050: No OtherClient online.[0m
[92m2024-02-29 14:13:29 I/Net 3079809050: Start loading group list...[0m
[0m2024-02-29 14:13:29 V/Net 3079809050: Recv: OidbSvc.0x496[0m
[92m2024-02-29 14:13:29 I/Net 3079809050: Syncing friend message history: Success.[0m
[0m2024-02-29 14:13:29 V/Net 3079809050: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[0m2024-02-29 14:13:29 V/Net 3079809050: Recv: friendlist.getFriendGroupList[0m
[0m2024-02-29 14:13:29 V/Net 3079809050: Loading friendGroup list: 1/1[0m
[92m2024-02-29 14:13:29 I/Net 3079809050: Successfully loaded friendGroup list: 1 in total[0m
[0m2024-02-29 14:13:29 V/Net 3079809050: Recv: friendlist.getFriendGroupList[0m
[0m2024-02-29 14:13:29 V/Net 3079809050: Loading friend list: 2/2[0m
[92m2024-02-29 14:13:29 I/Net 3079809050: Successfully loaded friend list: 2 in total[0m
[0m2024-02-29 14:13:29 V/Net 3079809050: Recv: friendlist.GetTroopListReqV2[0m
[92m2024-02-29 14:13:29 I/Net 3079809050: Successfully loaded group list: 0 in total.[0m
[92m2024-02-29 14:13:29 I/Net 3079809050: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[92m2024-02-29 14:13:29 I/Net 3079809050: Scheduled key refresh in 23h 55min 0.0s.[0m
[0m2024-02-29 14:13:32 V/Net 3079809050: Server list: 153.3.149.95:80, 111.206.149.168:443, msfwifi.3g.qq.com:8080, 157.148.55.96:14000, 157.255.5.249:80, 123.125.0.210:14000, 123.125.0.210:80, 157.148.54.16:80, 220.194.118.230:8080, 112.86.230.139:14000.[0m
[0m2024-02-29 14:13:32 V/Net 3079809050: No BdhSession to save to cache[0m
[0m2024-02-29 14:13:32 V/Net 3079809050: Saving server list to cache[0m
[0m2024-02-29 14:13:32 V/Net 3079809050: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2024-02-29 14:13:32 V/Net 3079809050: Recv: ConfigPushSvc.PushReq[0m
[0m2024-02-29 14:13:32 V/Net 3079809050: Saving bdh session to cache[0m
[0m2024-02-29 14:13:32 V/Net 3079809050: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2024-02-29 14:13:32 V/Net 3079809050: Recv: ConfigPushSvc.PushReq[0m
[0m2024-02-29 14:14:31 V/Net 3079809050: Send: StatSvc.register(offline)[0m
